# Generated by Django 3.0.3 on 2020-04-17 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebook', '0004_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ebook',
            name='isbn',
        ),
        migrations.RemoveField(
            model_name='ebook',
            name='price',
        ),
    ]
